apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: metallb-config
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  wait: true
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          app: metallb
  resources:
    - apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: kind-pool
        namespace: metallb-system
      spec:
        addresses:
          - << inputs.addressRange >>
        autoAssign: true
    - apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: kind-l2
        namespace: metallb-system
      spec:
        ipAddressPools:
          - kind-pool
