apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - rbac.yaml
  - source.yaml
  - cert-manager.yaml
  - cloudflare.yaml
  - istio.yaml
  - kyverno.yaml
  - monitoring.yaml
  - opa.yaml
  - reflector.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: infra
