apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/istio.yaml
  - istio.yaml

labels:
  - pairs:
      env: app-dev
    includeSelectors: true
    includeTemplates: true